# Generated by Django 5.0.6 on 2024-06-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendorAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('vendorappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendorapp.vendorappmodel')),
                ('name', models.CharField(max_length=100)),
                ('firearm_type', models.CharField(choices=[('PISTOL', 'PISTOL'), ('PISTOL2', 'PISTO2')], max_length=50)),
            ],
            bases=('vendorapp.vendorappmodel',),
        ),
    ]
