# Generated by Django 5.0.6 on 2024-06-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('clientappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientapp.clientappmodel')),
                ('first_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('ID_Number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            bases=('clientapp.clientappmodel',),
        ),
        migrations.CreateModel(
            name='ClientDocuments',
            fields=[
                ('clientappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientapp.clientappmodel')),
                ('file', models.FileField(upload_to='client/profile')),
                ('tag', models.CharField(choices=[('ID', 'ID'), ('GOODCONDUCT', 'GOODCONDUCT'), ('PROFILE', 'PROFILE')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_documents', to='clientapp.clientprofile')),
            ],
            bases=('clientapp.clientappmodel',),
        ),
    ]
