# Generated by Django 5.0.6 on 2024-06-11 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
        ('vendorapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('clientappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientapp.clientappmodel')),
                ('next_of_kin_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('type_of_firearm', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_application', to='clientapp.clientprofile')),
            ],
            bases=('clientapp.clientappmodel',),
        ),
        migrations.CreateModel(
            name='ClientFirearm',
            fields=[
                ('clientappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientapp.clientappmodel')),
                ('status', models.CharField(choices=[('Armed', 'Armed'), ('Disarmed', 'Disarmed')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_firearm', to='clientapp.clientprofile')),
                ('firearm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assigned_firearm', to='vendorapp.firearm')),
            ],
            bases=('clientapp.clientappmodel',),
        ),
    ]
